controller_manager:
  ros__parameters:
    #use_sim_time: True
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
  #had to add a separate use_sim_time here for humble compatibility
    use_sim_time: True
    publish_rate: 50.0

    base_frame_id: base_footprint

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.297
    wheel_radius: 0.033

    use_stamped_vel: false
    enable_odom_tf: False
